name: flutter_atm
description: Test task ATM on the Flutter for Tages Jump.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # App architecture
  flutter_bloc: ^3.2.0
  # Freezed annotation
  freezed_annotation:
  # Dependency Injection (DI)
  get_it: ^4.0.0-release-candidate
  # Injectable for DI
  injectable: ^0.2.3
  # Animations
  simple_animations: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  # No version number means the latest version
  build_runner:
  # Generators
  freezed: ^0.7.0
  injectable_generator: ^0.2.2

flutter:
  uses-material-design: true