name: flutter_atm
description: Test task ATM on the Flutter for Tages Jump.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # App architecture
  flutter_bloc: ^3.2.0
  # Sealed classes for states & events
  super_enum: ^0.3.0
  # Dependency Injection (DI)
  get_it: ^4.0.0-beta3
  # Animation
  simple_animations: ^1.3.6
  # No version number means the latest version
  build_runner:
  # Generators
  super_enum_generator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true